# Always rendered (like the server ServiceAccount itself): the server reads the kube-system
# namespace UID as its installation fingerprint. Without this grant it logs a boot warning and
# falls back to a persisted random id, and an offline license file bound to a fingerprint list
# refuses to start.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubemq.clusterLicenseRoleName" . }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: ["kube-system"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubemq.clusterLicenseCrbName" . }}
subjects:
  - kind: ServiceAccount
    name: kubemq-cluster-next
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubemq.clusterLicenseRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
