{{- if .Values.operator.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubemq.crbName" . }}
subjects:
  - kind: ServiceAccount
    name: kubemq-operator-next
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubemq.operatorRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
