{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemq-operator-next
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemq-cluster-next
  namespace: {{ .Release.Namespace }}
